import os
from dotenv import load_dotenv

# Load environment variables from the root project folder
load_dotenv(os.path.join(os.path.dirname(__file__), "../../../.env"))

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Dict, Any

from models.domain import SkillTree

from fastapi.responses import RedirectResponse

app = FastAPI(
    title="Nexus-Learn API",
    description="Skill-Tree Micro-Learning Engine backend service.",
    version="1.0.0",
)

# Allow CORS for Next.js frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["https://hack-srm-one.vercel.app"],  # Adjust this to point to the Next.js frontend in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/", include_in_schema=False)
async def root():
    """Redirect root to API documentation."""
    return RedirectResponse(url="/docs")

class GenerateTreeRequest(BaseModel):
    skill: str

class VerifyRequest(BaseModel):
    answer: str

from agents.architect import architect_agent

@app.post("/tree/generate", response_model=SkillTree)
async def generate_skill_tree(request: GenerateTreeRequest):
    """
    Accepts a skill string, returns the full DAG structure created by the Architect Agent.
    """
    initial_state = {"skill": request.skill, "tree": None, "error": None}
    
    # Run the graph
    result_state = await architect_agent.ainvoke(initial_state)
    
    if result_state.get("error"):
        raise HTTPException(status_code=500, detail=result_state["error"])
        
    tree = result_state.get("tree")
    if not tree:
        raise HTTPException(status_code=500, detail="Failed to generate the skill tree.")
        
    return tree

@app.get("/node/{id}/content")
async def get_node_content(id: str):
    """
    Returns the markdown lesson content generated by the Content Generator.
    """
    # TODO: Check DB for cached content. If None, invoke LangGraph Content Generator Agent.
    raise HTTPException(status_code=501, detail="Content generation pending implementation.")

@app.post("/node/{id}/verify")
async def verify_node_quiz(id: str, request: VerifyRequest):
    """
    Validates quiz answers using the Gatekeeper Agent and updates DB progress if passed.
    """
    # TODO: Fetch content and answer, invoke Gatekeeper Agent, unlock nodes on success.
    raise HTTPException(status_code=501, detail="Gatekeeper logic pending implementation.")

@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {"status": "healthy"}
